version: "3.9"
services:
  rstudio:
    build:
      context: docker
      dockerfile: Dockerfile
    image: otho/flexdashboard2
    ports:
      - "8787:8787"
    volumes:
      - type: "bind"
        source: "$TUTORIAL_WORKING_DIR"
        target: "/home/rstudio"
      - type: "bind"
        source: "$RSTUDIO_CONFIG_PATH"
        target: "/home/rstudio/.config/rstudio"